# Generated by Django 4.1.1 on 2022-10-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='profile/avatar2.jpg', upload_to='profile'),
        ),
    ]
